import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

const bannedIconMessage =
  'Decorative sparkle/star icons are banned in BountyFlow. Use a meaningful lucide icon instead.'

export default tseslint.config(
  // src/bones is generated by `pnpm bones` (boneyard skeleton captures).
  { ignores: ['dist', 'coverage', 'playwright-report', 'test-results', 'node_modules', 'src/bones'] },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      globals: { ...globals.browser },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs['recommended-latest'].rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'lucide-react',
              importNames: [
                'Sparkles',
                'Sparkle',
                'Stars',
                'WandSparkles',
                'SparklesIcon',
                'SparkleIcon',
                'StarsIcon',
                'WandSparklesIcon',
                'LucideSparkles',
                'LucideSparkle',
                'LucideStars',
                'LucideWandSparkles',
              ],
              message: bannedIconMessage,
            },
          ],
        },
      ],
    },
  },
  {
    // shadcn/ui primitives export variants alongside components by design.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/set-state-in-effect': 'off',
    },
  },
  {
    files: ['**/*.test.{ts,tsx}', 'src/__tests__/**', 'src/test/**'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    files: ['*.config.{js,ts}', 'e2e/**/*.ts'],
    languageOptions: { globals: { ...globals.node } },
  },
)
