# BountyFlow — developer and operations commands.
#
# Shell: GNU Make with bash (Linux/macOS, or Git Bash on Windows). Run `make help` for the list.
# Prerequisites: Docker (Desktop), uv, Node.js 22 + pnpm, Rust + Stellar CLI (contract targets only).

SHELL := bash
.SHELLFLAGS := -eu -o pipefail -c
.DEFAULT_GOAL := help

BACKEND  := backend
FRONTEND := frontend
CONTRACT := contracts
COMPOSE  := docker compose
UV       := uv --directory $(BACKEND) run
PNPM     := pnpm --dir $(FRONTEND)

.PHONY: help install env dev api worker frontend-dev up up-tools infra down restart logs ps build \
        migrate migration seed reset-db db-shell test test-api test-api-unit test-api-integration \
        test-testnet test-frontend test-e2e bones lint format typecheck check contract-build contract-test \
        contract-deploy-testnet audit clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-24s\033[0m %s\n", $$1, $$2}'

# --- Setup ---------------------------------------------------------------------------------

env: ## Create .env from .env.example (never overwrites an existing .env)
	@if [ -f .env ]; then echo ".env already exists — leaving it untouched"; else \
	  cp .env.example .env && \
	  secret=$$(python -c "import secrets; print(secrets.token_urlsafe(48))") && \
	  sed -i.bak "s|^JWT_SECRET=.*|JWT_SECRET=$$secret|" .env && rm -f .env.bak && \
	  echo "Created .env with a fresh JWT_SECRET"; fi

install: env ## Install backend (uv) and frontend (pnpm) dependencies
	cd $(BACKEND) && uv sync
	$(PNPM) install
	$(PNPM) exec playwright install chromium

# --- Local development ----------------------------------------------------------------------

# Named by what it leaves out rather than what it starts, so a service added to docker-compose.yml is
# included automatically instead of being silently missed here. The frontend and the backend (API,
# worker and the migration job) are the pieces you run yourself during development.
infra: ## Start every service except the frontend and the backend (API, worker, migrations)
	$(COMPOSE) up -d --scale frontend=0 --scale api=0 --scale worker=0 --scale migrate=0 --scale kafka-init=0
	$(COMPOSE) up kafka-init

dev: infra migrate seed ## Run infra in Docker and API + worker + frontend on the host (Ctrl+C stops all)
	@echo "API http://localhost:8000/api/docs · App http://localhost:5173 · Mail http://localhost:8025"
	@trap 'kill 0' INT TERM; \
	  ( $(UV) python -m app.serve ) & \
	  ( $(UV) python -m worker.main ) & \
	  ( $(PNPM) dev ) & \
	  wait

api: ## Run the API on the host (selector event loop; works on Windows)
	$(UV) python -m app.serve

worker: ## Run the background worker on the host
	$(UV) python -m worker.main

frontend-dev: ## Run the Vite dev server
	$(PNPM) dev

# --- Docker Compose ---------------------------------------------------------------------------

up: env ## Build and start the full stack in Docker (app on http://localhost:3000)
	$(COMPOSE) up -d --build
	@echo "App http://localhost:3000 · API http://localhost:8000/api/docs · Mail http://localhost:8025"

up-tools: ## Start the stack plus Kafka UI (http://localhost:8080)
	$(COMPOSE) --profile tools up -d --build

down: ## Stop containers (keeps data volumes)
	$(COMPOSE) --profile tools down

restart: ## Restart application containers
	$(COMPOSE) restart api worker frontend

logs: ## Tail logs of application containers
	$(COMPOSE) logs -f --tail=200 api worker frontend

ps: ## Show container status
	$(COMPOSE) ps

build: ## Build production images and the frontend bundle
	$(COMPOSE) build
	$(PNPM) build

# --- Database ------------------------------------------------------------------------------

migrate: ## Apply database migrations (alembic upgrade head)
	$(UV) alembic upgrade head

migration: ## Create a new autogenerated migration: make migration m="describe change"
	@test -n "$(m)" || (echo 'Usage: make migration m="describe change"' && exit 1)
	$(UV) alembic revision --autogenerate -m "$(m)"

seed: ## Seed accounts and bounties (idempotent) and print the sign-in details
	$(UV) python -m app.scripts.seed

reset-db: ## DESTRUCTIVE: drop and recreate the dev database, then migrate + seed (asks for confirmation)
	@read -r -p "This deletes ALL local BountyFlow data. Type 'reset' to continue: " ans; \
	  [ "$$ans" = "reset" ] || (echo "Aborted." && exit 1)
	$(COMPOSE) exec -T postgres psql -U $${POSTGRES_USER:-bountyflow} -d postgres \
	  -c "DROP DATABASE IF EXISTS $${POSTGRES_DB:-bountyflow} WITH (FORCE);" \
	  -c "CREATE DATABASE $${POSTGRES_DB:-bountyflow};"
	$(MAKE) migrate seed

db-shell: ## Open psql in the database container
	$(COMPOSE) exec postgres psql -U $${POSTGRES_USER:-bountyflow} -d $${POSTGRES_DB:-bountyflow}

# --- Quality -------------------------------------------------------------------------------

test: test-api test-frontend contract-test ## Run backend, frontend and contract test suites

test-api: ## Backend unit + integration tests (integration uses the isolated bountyflow_test DB)
	$(UV) pytest -q

test-api-unit: ## Backend unit tests only (no infrastructure required)
	$(UV) pytest tests/unit -q

test-api-integration: ## Backend integration tests against bountyflow_test
	$(UV) pytest tests/integration -q -m integration

test-testnet: ## OPT-IN: full lifecycle on the real Stellar Testnet (needs running API + Friendbot)
	RUN_TESTNET_E2E=1 $(UV) pytest tests/contract/test_testnet_flow.py -m testnet -s

test-frontend: ## Frontend unit/component tests (Vitest)
	$(PNPM) test

test-e2e: ## Playwright end-to-end tests (expects the app running; see docs/testing.md)
	$(PNPM) test:e2e

bones: ## Recapture loading skeletons from the running app (seeded API + dev server; see docs/development.md)
	$(PNPM) bones

lint: ## Lint backend (ruff) and frontend (eslint)
	$(UV) ruff check app worker tests
	$(UV) ruff format --check app worker tests
	$(PNPM) lint

format: ## Auto-format backend and frontend
	$(UV) ruff check --fix app worker tests
	$(UV) ruff format app worker tests
	$(PNPM) format

typecheck: ## Type-check backend (mypy) and frontend (tsc)
	$(UV) mypy app worker
	$(PNPM) typecheck

check: lint typecheck test ## Everything CI runs

audit: ## Dependency vulnerability scan (pip-audit on the locked backend deps + pnpm audit)
	cd $(BACKEND) && uv export --frozen --no-dev --no-emit-project --format requirements-txt --quiet -o .audit-requirements.txt \
	  && uvx pip-audit --strict --disable-pip --require-hashes -r .audit-requirements.txt; \
	  status=$$?; rm -f .audit-requirements.txt; exit $$status
	$(PNPM) audit --prod

# --- Soroban contract ------------------------------------------------------------------------

contract-build: ## Build the escrow contract wasm (stellar contract build)
	$(MAKE) -C $(CONTRACT)/bounty_escrow build

contract-test: ## Run contract unit tests (cargo test)
	cd $(CONTRACT) && cargo test

contract-deploy-testnet: ## Deploy the escrow contract to Stellar Testnet (needs Stellar CLI; writes contracts/deployments/testnet.json)
	bash scripts/deploy-contract.sh

# --- Housekeeping ----------------------------------------------------------------------------

clean: ## Remove build artefacts and caches (keeps Docker volumes and .env)
	rm -rf $(FRONTEND)/dist $(FRONTEND)/playwright-report $(FRONTEND)/test-results
	find $(BACKEND) -type d \( -name __pycache__ -o -name .pytest_cache -o -name .mypy_cache -o -name .ruff_cache \) -prune -exec rm -rf {} +
	cd $(CONTRACT) && cargo clean
