"""Alembic environment: async engine (psycopg 3) configured from application settings."""

from __future__ import annotations

import asyncio
import copy
import os
import sys
from collections.abc import Iterator
from logging.config import fileConfig
from typing import Any

import sqlalchemy as sa
from alembic import context
from alembic.operations import ops
from alembic.script import ScriptDirectory
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

import app.db.models  # noqa: F401  - registers every table on Base.metadata
from app.core.config import get_settings
from app.db.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# Base.metadata carries the naming convention, so autogenerated constraint/index names are deterministic.
target_metadata = Base.metadata

# The database may be shared with another project, whose Alembic would otherwise read and overwrite the
# same ``alembic_version`` row and lose track of its own schema.
LEGACY_VERSION_TABLE = "alembic_version"
VERSION_TABLE = "bountyflow_alembic_version"


def database_url() -> str:
    """Precedence: `alembic -x db_url=...`, then ALEMBIC_DATABASE_URL, then application settings."""
    return (
        context.get_x_argument(as_dictionary=True).get("db_url")
        or os.environ.get("ALEMBIC_DATABASE_URL")
        or get_settings().database_url
    )


def _known_revisions() -> set[str]:
    return {script.revision for script in ScriptDirectory.from_config(config).walk_revisions()}


def _adopt_version_table(connection: Connection) -> None:
    """Take over a database still stamped in Alembic's default ``alembic_version``.

    Alembic resolves its version table before it runs a single migration, so 0013 cannot do this itself:
    a database at 0012 would look empty and replay from 0001 onto tables that already exist. On a shared
    database ``alembic_version`` may be another project's, so it is only claimed when it holds one of
    this project's own revisions.
    """
    inspector = sa.inspect(connection)
    if inspector.has_table(VERSION_TABLE) or not inspector.has_table(LEGACY_VERSION_TABLE):
        return
    statement = f"SELECT version_num FROM {LEGACY_VERSION_TABLE}"  # noqa: S608 - a module constant
    stamped = set(connection.scalars(sa.text(statement)))
    if not stamped or not stamped <= _known_revisions():
        return
    connection.exec_driver_sql(f"ALTER TABLE {LEGACY_VERSION_TABLE} RENAME TO {VERSION_TABLE}")
    primary_key = connection.scalar(
        sa.text(
            "SELECT conname FROM pg_constraint WHERE conrelid = CAST(:table AS regclass) AND contype = 'p'"
        ),
        {"table": VERSION_TABLE},
    )
    if primary_key:
        connection.exec_driver_sql(
            f'ALTER TABLE {VERSION_TABLE} RENAME CONSTRAINT "{primary_key}" TO "{VERSION_TABLE}_pkc"'
        )


def _adopt_version_table_sql() -> str:
    """The same adoption as one guarded statement, so ``alembic upgrade --sql`` emits it too."""
    revisions = ", ".join(f"'{revision}'" for revision in sorted(_known_revisions()))
    return f"""
DO $$
DECLARE
    stamped text;
    primary_key text;
BEGIN
    IF to_regclass('{VERSION_TABLE}') IS NOT NULL OR to_regclass('{LEGACY_VERSION_TABLE}') IS NULL THEN
        RETURN;
    END IF;
    SELECT version_num INTO stamped FROM {LEGACY_VERSION_TABLE};
    IF stamped IS NULL OR stamped NOT IN ({revisions}) THEN
        RETURN;
    END IF;
    ALTER TABLE {LEGACY_VERSION_TABLE} RENAME TO {VERSION_TABLE};
    SELECT conname INTO primary_key
    FROM pg_constraint WHERE conrelid = '{VERSION_TABLE}'::regclass AND contype = 'p';
    IF primary_key IS NOT NULL THEN
        EXECUTE format('ALTER TABLE {VERSION_TABLE} RENAME CONSTRAINT %I TO %I', primary_key,
                       '{VERSION_TABLE}_pkc');
    END IF;
END $$
"""  # noqa: S608 - module constants and this project's own revision ids


def _walk_ops(container: Any) -> Iterator[Any]:
    for op in getattr(container, "ops", []):
        yield op
        yield from _walk_ops(op)


def _normalize_where(kw: dict[str, Any]) -> None:
    where = kw.get("postgresql_where")
    if isinstance(where, str):
        kw["postgresql_where"] = sa.text(where)


def _fix_autogenerate(_context: Any, _revision: Any, directives: list[Any]) -> None:
    """Post-process autogenerated operations so the output is correct without hand edits:

    * ``str_enum`` columns (VARCHAR + CHECK) are rendered by Alembic as ``sa.Enum(create_constraint=True)`` plus
      the same CHECK constraint again at table level (twice), which fails with DuplicateObject. Keep exactly one
      explicit, convention-named CHECK per enum and render the column type with ``create_constraint=False``.
    * Partial-index predicates declared as strings are rendered as ``sa.text(...)``.
    """
    if not directives:
        return
    script = directives[0]
    for upgrade_or_downgrade in (script.upgrade_ops, script.downgrade_ops):
        for op in _walk_ops(upgrade_or_downgrade):
            if isinstance(op, ops.CreateTableOp):
                kept: list[Any] = []
                seen_checks: dict[str, int] = {}
                for item in op.columns:
                    if (
                        isinstance(item, sa.Column)
                        and isinstance(item.type, sa.Enum)
                        and item.type.create_constraint
                    ):
                        enum_type = copy.copy(item.type)
                        enum_type.create_constraint = False
                        item.type = enum_type
                    if isinstance(item, sa.CheckConstraint):
                        key = str(item.sqltext)
                        if key in seen_checks:
                            # prefer the convention-named variant (``ck_<table>_<name>``)
                            if str(item.name or "").startswith("ck_"):
                                kept[seen_checks[key]] = item
                            continue
                        seen_checks[key] = len(kept)
                    kept.append(item)
                op.columns = kept
            elif isinstance(op, ops.CreateIndexOp | ops.DropIndexOp):
                _normalize_where(op.kw)


def _configure(**kwargs: object) -> None:
    context.configure(
        target_metadata=target_metadata,
        version_table=VERSION_TABLE,
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
        include_schemas=False,
        process_revision_directives=_fix_autogenerate,
        **kwargs,  # type: ignore[arg-type]
    )


def run_migrations_offline() -> None:
    _configure(url=database_url(), literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.execute(_adopt_version_table_sql())
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    engine = create_async_engine(database_url(), poolclass=pool.NullPool)
    try:
        async with engine.connect() as connection:
            # Committed on its own, before Alembic opens the migration transaction and reads the version.
            await connection.run_sync(_adopt_version_table)
            await connection.commit()
            await connection.run_sync(do_run_migrations)
    finally:
        await engine.dispose()


def run_migrations_online() -> None:
    # psycopg's async driver requires a selector event loop; Windows defaults to the proactor loop.
    loop_factory = asyncio.SelectorEventLoop if sys.platform == "win32" else None
    asyncio.run(run_async_migrations(), loop_factory=loop_factory)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
