"""Alembic environment: async engine (psycopg 3) configured from application settings."""

from __future__ import annotations

import asyncio
import copy
import os
import sys
from collections.abc import Iterator
from logging.config import fileConfig
from typing import Any

import sqlalchemy as sa
from alembic import context
from alembic.operations import ops
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

import app.db.models  # noqa: F401  - registers every table on Base.metadata
from app.core.config import get_settings
from app.db.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# Base.metadata carries the naming convention, so autogenerated constraint/index names are deterministic.
target_metadata = Base.metadata


def database_url() -> str:
    """Precedence: `alembic -x db_url=...`, then ALEMBIC_DATABASE_URL, then application settings."""
    return (
        context.get_x_argument(as_dictionary=True).get("db_url")
        or os.environ.get("ALEMBIC_DATABASE_URL")
        or get_settings().database_url
    )


def _walk_ops(container: Any) -> Iterator[Any]:
    for op in getattr(container, "ops", []):
        yield op
        yield from _walk_ops(op)


def _normalize_where(kw: dict[str, Any]) -> None:
    where = kw.get("postgresql_where")
    if isinstance(where, str):
        kw["postgresql_where"] = sa.text(where)


def _fix_autogenerate(_context: Any, _revision: Any, directives: list[Any]) -> None:
    """Post-process autogenerated operations so the output is correct without hand edits:

    * ``str_enum`` columns (VARCHAR + CHECK) are rendered by Alembic as ``sa.Enum(create_constraint=True)`` plus
      the same CHECK constraint again at table level (twice), which fails with DuplicateObject. Keep exactly one
      explicit, convention-named CHECK per enum and render the column type with ``create_constraint=False``.
    * Partial-index predicates declared as strings are rendered as ``sa.text(...)``.
    """
    if not directives:
        return
    script = directives[0]
    for upgrade_or_downgrade in (script.upgrade_ops, script.downgrade_ops):
        for op in _walk_ops(upgrade_or_downgrade):
            if isinstance(op, ops.CreateTableOp):
                kept: list[Any] = []
                seen_checks: dict[str, int] = {}
                for item in op.columns:
                    if (
                        isinstance(item, sa.Column)
                        and isinstance(item.type, sa.Enum)
                        and item.type.create_constraint
                    ):
                        enum_type = copy.copy(item.type)
                        enum_type.create_constraint = False
                        item.type = enum_type
                    if isinstance(item, sa.CheckConstraint):
                        key = str(item.sqltext)
                        if key in seen_checks:
                            # prefer the convention-named variant (``ck_<table>_<name>``)
                            if str(item.name or "").startswith("ck_"):
                                kept[seen_checks[key]] = item
                            continue
                        seen_checks[key] = len(kept)
                    kept.append(item)
                op.columns = kept
            elif isinstance(op, ops.CreateIndexOp | ops.DropIndexOp):
                _normalize_where(op.kw)


def _configure(**kwargs: object) -> None:
    context.configure(
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        render_as_batch=False,
        include_schemas=False,
        process_revision_directives=_fix_autogenerate,
        **kwargs,  # type: ignore[arg-type]
    )


def run_migrations_offline() -> None:
    _configure(url=database_url(), literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    engine = create_async_engine(database_url(), poolclass=pool.NullPool)
    try:
        async with engine.connect() as connection:
            await connection.run_sync(do_run_migrations)
    finally:
        await engine.dispose()


def run_migrations_online() -> None:
    # psycopg's async driver requires a selector event loop; Windows defaults to the proactor loop.
    loop_factory = asyncio.SelectorEventLoop if sys.platform == "win32" else None
    asyncio.run(run_async_migrations(), loop_factory=loop_factory)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
