"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 18:28:43.412802+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('day', 'metric', name=op.f('pk_daily_metrics'))
    )
    op.create_table('outbox_events',
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=32), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('processed_events',
    sa.Column('consumer', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer', 'event_id', name=op.f('pk_processed_events'))
    )
    op.create_table('simulated_ledger_entries',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_simulated_ledger_entries'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('github_url', sa.String(length=300), nullable=True),
    sa.Column('portfolio_url', sa.String(length=300), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String(length=40)), server_default='{}', nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('wants_to_request', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('wants_to_contribute', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('USER', 'MODERATOR', 'ADMIN')", name=op.f('ck_users_user_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('normalized_email', name=op.f('uq_users_normalized_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('bounties',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('DEVELOPMENT', 'BUG_BOUNTY', 'DESIGN', 'SECURITY', 'DOCUMENTATION', 'RESEARCH', 'COMMUNITY', 'OTHER', name='bounty_category', native_enum=False, length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='bounty_difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('reward_asset', sa.String(length=64), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'FUNDING_PENDING', 'FUNDED', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLETED', 'CANCEL_REQUESTED', 'CANCELLED', 'DISPUTED', 'EXPIRED', name='bounty_status', native_enum=False, length=32), nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('positions_available', sa.Integer(), nullable=False),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('submission_requirements', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'UNLISTED', name='bounty_visibility', native_enum=False, length=32), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('applications_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bookmarks_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(short_description, '')), 'B') || setweight(to_tsvector('english', coalesce(description, '')), 'C')", persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('DEVELOPMENT', 'BUG_BOUNTY', 'DESIGN', 'SECURITY', 'DOCUMENTATION', 'RESEARCH', 'COMMUNITY', 'OTHER')", name=op.f('ck_bounties_bounty_category')),
    sa.CheckConstraint("difficulty IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT')", name=op.f('ck_bounties_bounty_difficulty')),
    sa.CheckConstraint("status IN ('DRAFT', 'OPEN', 'FUNDING_PENDING', 'FUNDED', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLETED', 'CANCEL_REQUESTED', 'CANCELLED', 'DISPUTED', 'EXPIRED')", name=op.f('ck_bounties_bounty_status')),
    sa.CheckConstraint("visibility IN ('PUBLIC', 'UNLISTED')", name=op.f('ck_bounties_bounty_visibility')),
    sa.CheckConstraint('application_deadline IS NULL OR completion_deadline IS NULL OR application_deadline <= completion_deadline', name=op.f('ck_bounties_deadline_order')),
    sa.CheckConstraint('positions_available >= 1 AND positions_available <= 100', name=op.f('ck_bounties_positions_range')),
    sa.CheckConstraint('reward_amount > 0', name=op.f('ck_bounties_reward_positive')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_bounties_requester_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounties')),
    sa.UniqueConstraint('slug', name=op.f('uq_bounties_slug'))
    )
    op.create_index(op.f('ix_bounties_category'), 'bounties', ['category'], unique=False)
    op.create_index(op.f('ix_bounties_difficulty'), 'bounties', ['difficulty'], unique=False)
    op.create_index(op.f('ix_bounties_requester_id'), 'bounties', ['requester_id'], unique=False)
    op.create_index('ix_bounties_requester_status', 'bounties', ['requester_id', 'status'], unique=False)
    op.create_index('ix_bounties_search_vector', 'bounties', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_bounties_status'), 'bounties', ['status'], unique=False)
    op.create_index('ix_bounties_status_published', 'bounties', ['status', 'published_at'], unique=False)
    op.create_table('email_deliveries',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='email_status', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'SENT', 'FAILED')", name=op.f('ck_email_deliveries_email_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_deliveries_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_deliveries')),
    sa.UniqueConstraint('idempotency_key', name='uq_email_deliveries_idempotency')
    )
    op.create_index(op.f('ix_email_deliveries_user_id'), 'email_deliveries', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verification_tokens_token_hash'))
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_notification_preferences'))
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('BOUNTY_PUBLISHED', 'BOUNTY_FUNDED', 'APPLICATION_RECEIVED', 'APPLICATION_ACCEPTED', 'APPLICATION_REJECTED', 'SUBMISSION_RECEIVED', 'REVISION_REQUESTED', 'SUBMISSION_APPROVED', 'SUBMISSION_REJECTED', 'PAYMENT_CONFIRMED', 'BOUNTY_CANCELLED', 'BOUNTY_EXPIRED', 'DISPUTE_UPDATE', 'SYSTEM', name='notification_type', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('BOUNTY_PUBLISHED', 'BOUNTY_FUNDED', 'APPLICATION_RECEIVED', 'APPLICATION_ACCEPTED', 'APPLICATION_REJECTED', 'SUBMISSION_RECEIVED', 'REVISION_REQUESTED', 'SUBMISSION_APPROVED', 'SUBMISSION_REJECTED', 'PAYMENT_CONFIRMED', 'BOUNTY_CANCELLED', 'BOUNTY_EXPIRED', 'DISPUTE_UPDATE', 'SYSTEM')", name=op.f('ck_notifications_notification_type')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('user_id', 'source_event_id', name='uq_notifications_user_event')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('BOUNTY', 'USER', 'SUBMISSION', name='report_target', native_enum=False, length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'REVIEWING', 'ACTIONED', 'DISMISSED', name='report_status', native_enum=False, length=32), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'REVIEWING', 'ACTIONED', 'DISMISSED')", name=op.f('ck_user_reports_report_status')),
    sa.CheckConstraint("target_type IN ('BOUNTY', 'USER', 'SUBMISSION')", name=op.f('ck_user_reports_report_target')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_user_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_user_reports_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_reports'))
    )
    op.create_index(op.f('ix_user_reports_reporter_id'), 'user_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_user_reports_status'), 'user_reports', ['status'], unique=False)
    op.create_index('ix_user_reports_target', 'user_reports', ['target_type', 'target_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_token_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_previous_token_hash'), 'user_sessions', ['previous_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skills')),
    sa.UniqueConstraint('user_id', 'skill_name', name=op.f('uq_user_skills_user_id_skill_name'))
    )
    op.create_index(op.f('ix_user_skills_skill_name'), 'user_skills', ['skill_name'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('public_address', sa.String(length=56), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'REVOKED', name='wallet_verification_status', native_enum=False, length=32), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('VERIFIED', 'REVOKED')", name=op.f('ck_wallets_wallet_verification_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets'))
    )
    op.create_index(op.f('ix_wallets_public_address'), 'wallets', ['public_address'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_index('uq_wallets_active_address_network', 'wallets', ['public_address', 'network'], unique=True, postgresql_where=sa.text("verification_status = 'VERIFIED'"))
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('bounty_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_audit_logs_bounty_id_bounties'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_bounty_created', 'audit_logs', ['bounty_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('bounty_applications',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('cover_message', sa.Text(), nullable=False),
    sa.Column('relevant_experience', sa.Text(), nullable=True),
    sa.Column('work_samples', postgresql.ARRAY(sa.String(length=500)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='application_status', native_enum=False, length=32), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN')", name=op.f('ck_bounty_applications_application_status')),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_applications_bounty_id_bounties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_bounty_applications_contributor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_bounty_applications_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_applications'))
    )
    op.create_index('ix_applications_bounty_status', 'bounty_applications', ['bounty_id', 'status'], unique=False)
    op.create_index(op.f('ix_bounty_applications_bounty_id'), 'bounty_applications', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_applications_contributor_id'), 'bounty_applications', ['contributor_id'], unique=False)
    op.create_index('uq_applications_one_active', 'bounty_applications', ['bounty_id', 'contributor_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'ACCEPTED')"))
    op.create_table('bounty_bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_bookmarks_bounty_id_bounties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bounty_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_bookmarks')),
    sa.UniqueConstraint('user_id', 'bounty_id', name=op.f('uq_bounty_bookmarks_user_id_bounty_id'))
    )
    op.create_index(op.f('ix_bounty_bookmarks_bounty_id'), 'bounty_bookmarks', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_bookmarks_user_id'), 'bounty_bookmarks', ['user_id'], unique=False)
    op.create_table('bounty_escrows',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.String(length=56), nullable=True),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('onchain_bounty_id', sa.String(length=64), nullable=False),
    sa.Column('asset_identifier', sa.String(length=80), nullable=False),
    sa.Column('asset_contract_id', sa.String(length=56), nullable=True),
    sa.Column('reward_per_position', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('required_amount', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('funded_amount', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('paid_out_amount', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('requester_address', sa.String(length=56), nullable=True),
    sa.Column('arbiter_address', sa.String(length=56), nullable=True),
    sa.Column('onchain_deadline', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('NOT_CREATED', 'AWAITING_FUNDING', 'FUNDED', 'CANCEL_REQUESTED', 'DISPUTED', 'COMPLETED', 'CANCELLED', name='escrow_state', native_enum=False, length=32), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('NOT_CREATED', 'AWAITING_FUNDING', 'FUNDED', 'CANCEL_REQUESTED', 'DISPUTED', 'COMPLETED', 'CANCELLED')", name=op.f('ck_bounty_escrows_escrow_state')),
    sa.CheckConstraint('funded_amount >= 0 AND paid_out_amount >= 0 AND refunded_amount >= 0', name=op.f('ck_bounty_escrows_amounts')),
    sa.CheckConstraint('paid_out_amount + refunded_amount <= funded_amount', name=op.f('ck_bounty_escrows_conservation')),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_escrows_bounty_id_bounties'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_escrows')),
    sa.UniqueConstraint('bounty_id', name=op.f('uq_bounty_escrows_bounty_id')),
    sa.UniqueConstraint('onchain_bounty_id', name=op.f('uq_bounty_escrows_onchain_bounty_id'))
    )
    op.create_table('bounty_skills',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_skills_bounty_id_bounties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_skills')),
    sa.UniqueConstraint('bounty_id', 'skill_name', name=op.f('uq_bounty_skills_bounty_id_skill_name'))
    )
    op.create_index(op.f('ix_bounty_skills_bounty_id'), 'bounty_skills', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_skills_skill_name'), 'bounty_skills', ['skill_name'], unique=False)
    op.create_table('bounty_tags',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_tags_bounty_id_bounties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_tags')),
    sa.UniqueConstraint('bounty_id', 'tag', name=op.f('uq_bounty_tags_bounty_id_tag'))
    )
    op.create_index(op.f('ix_bounty_tags_bounty_id'), 'bounty_tags', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_tags_tag'), 'bounty_tags', ['tag'], unique=False)
    op.create_table('bounty_view_daily',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_view_daily_bounty_id_bounties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bounty_id', 'day', name=op.f('pk_bounty_view_daily'))
    )
    op.create_table('disputes',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='dispute_status', native_enum=False, length=32), nullable=False),
    sa.Column('assigned_moderator_id', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Enum('RELEASE_TO_CONTRIBUTOR', 'REFUND_TO_REQUESTER', 'DISMISSED', name='dispute_resolution', native_enum=False, length=32), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_before', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resolution IN ('RELEASE_TO_CONTRIBUTOR', 'REFUND_TO_REQUESTER', 'DISMISSED')", name=op.f('ck_disputes_dispute_resolution')),
    sa.CheckConstraint("status IN ('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED')", name=op.f('ck_disputes_dispute_status')),
    sa.ForeignKeyConstraint(['assigned_moderator_id'], ['users.id'], name=op.f('fk_disputes_assigned_moderator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_disputes_bounty_id_bounties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_disputes_contributor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], name=op.f('fk_disputes_raised_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_disputes_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_index(op.f('ix_disputes_bounty_id'), 'disputes', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_disputes_raised_by_id'), 'disputes', ['raised_by_id'], unique=False)
    op.create_index('uq_disputes_one_open_per_bounty', 'disputes', ['bounty_id'], unique=True, postgresql_where=sa.text("status IN ('OPEN', 'UNDER_REVIEW')"))
    op.create_table('bounty_assignments',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'RELEASED', name='assignment_status', native_enum=False, length=32), nullable=False),
    sa.Column('onchain_assigned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'RELEASED')", name=op.f('ck_bounty_assignments_assignment_status')),
    sa.ForeignKeyConstraint(['application_id'], ['bounty_applications.id'], name=op.f('fk_bounty_assignments_application_id_bounty_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_assignments_bounty_id_bounties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_bounty_assignments_contributor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_assignments')),
    sa.UniqueConstraint('application_id', name=op.f('uq_bounty_assignments_application_id'))
    )
    op.create_index(op.f('ix_bounty_assignments_bounty_id'), 'bounty_assignments', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_assignments_contributor_id'), 'bounty_assignments', ['contributor_id'], unique=False)
    op.create_index('uq_assignments_one_live', 'bounty_assignments', ['bounty_id', 'contributor_id'], unique=True, postgresql_where=sa.text("status IN ('ACTIVE', 'COMPLETED')"))
    op.create_table('dispute_evidence',
    sa.Column('dispute_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_dispute_evidence_dispute_id_disputes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_dispute_evidence_submitted_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispute_evidence'))
    )
    op.create_index(op.f('ix_dispute_evidence_dispute_id'), 'dispute_evidence', ['dispute_id'], unique=False)
    op.create_table('bounty_submissions',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('evidence_links', postgresql.ARRAY(sa.String(length=500)), server_default='{}', nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'REVISION_REQUESTED', 'RESUBMITTED', 'APPROVED', 'REJECTED', name='submission_status', native_enum=False, length=32), nullable=False),
    sa.Column('review_feedback', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('SUBMITTED', 'REVISION_REQUESTED', 'RESUBMITTED', 'APPROVED', 'REJECTED')", name=op.f('ck_bounty_submissions_submission_status')),
    sa.ForeignKeyConstraint(['assignment_id'], ['bounty_assignments.id'], name=op.f('fk_bounty_submissions_assignment_id_bounty_assignments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_bounty_submissions_bounty_id_bounties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_bounty_submissions_contributor_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_bounty_submissions_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bounty_submissions'))
    )
    op.create_index(op.f('ix_bounty_submissions_assignment_id'), 'bounty_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_bounty_submissions_bounty_id'), 'bounty_submissions', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_bounty_submissions_contributor_id'), 'bounty_submissions', ['contributor_id'], unique=False)
    op.create_table('blockchain_transactions',
    sa.Column('bounty_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=80), nullable=True),
    sa.Column('transaction_type', sa.Enum('ESCROW_CREATE', 'ESCROW_FUND', 'ASSIGN', 'PAYOUT', 'CANCEL_REQUEST', 'CANCEL_CONSENT', 'REFUND', 'DISPUTE_RAISE', 'DISPUTE_RESOLVE', 'WALLET_CHALLENGE', name='tx_type', native_enum=False, length=32), nullable=False),
    sa.Column('network', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=7), nullable=True),
    sa.Column('asset_identifier', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SIGNATURE_REQUIRED', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'EXPIRED', name='tx_status', native_enum=False, length=32), nullable=False),
    sa.Column('source_address', sa.String(length=56), nullable=True),
    sa.Column('destination_address', sa.String(length=56), nullable=True),
    sa.Column('contract_id', sa.String(length=56), nullable=True),
    sa.Column('function_name', sa.String(length=40), nullable=True),
    sa.Column('unsigned_xdr', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fee_stroops', sa.Integer(), nullable=True),
    sa.Column('ledger_sequence', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verification_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('CREATED', 'SIGNATURE_REQUIRED', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'EXPIRED')", name=op.f('ck_blockchain_transactions_tx_status')),
    sa.CheckConstraint("transaction_type IN ('ESCROW_CREATE', 'ESCROW_FUND', 'ASSIGN', 'PAYOUT', 'CANCEL_REQUEST', 'CANCEL_CONSENT', 'REFUND', 'DISPUTE_RAISE', 'DISPUTE_RESOLVE', 'WALLET_CHALLENGE')", name=op.f('ck_blockchain_transactions_tx_type')),
    sa.ForeignKeyConstraint(['assignment_id'], ['bounty_assignments.id'], name=op.f('fk_blockchain_transactions_assignment_id_bounty_assignments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_blockchain_transactions_bounty_id_bounties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_blockchain_transactions_dispute_id_disputes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['bounty_submissions.id'], name=op.f('fk_blockchain_transactions_submission_id_bounty_submissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blockchain_transactions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockchain_transactions')),
    sa.UniqueConstraint('network', 'transaction_hash', name='uq_blockchain_transactions_network_hash')
    )
    op.create_index(op.f('ix_blockchain_transactions_assignment_id'), 'blockchain_transactions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_bounty_id'), 'blockchain_transactions', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_submission_id'), 'blockchain_transactions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_blockchain_transactions_user_id'), 'blockchain_transactions', ['user_id'], unique=False)
    op.create_index('ix_blockchain_tx_bounty_created', 'blockchain_transactions', ['bounty_id', 'created_at'], unique=False)
    op.create_index('ix_blockchain_tx_status', 'blockchain_transactions', ['status'], unique=False)
    op.create_table('submission_revisions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('evidence_links', postgresql.ARRAY(sa.String(length=500)), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['bounty_submissions.id'], name=op.f('fk_submission_revisions_submission_id_bounty_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_revisions')),
    sa.UniqueConstraint('submission_id', 'version', name=op.f('uq_submission_revisions_submission_id_version'))
    )
    op.create_index(op.f('ix_submission_revisions_submission_id'), 'submission_revisions', ['submission_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('blockchain_transaction_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=7), nullable=False),
    sa.Column('asset_identifier', sa.String(length=80), nullable=False),
    sa.Column('payment_status', sa.Enum('NOT_REQUIRED', 'CREATED', 'SIGNATURE_REQUIRED', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'REFUND_PENDING', 'REFUNDED', name='payment_status', native_enum=False, length=32), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('NOT_REQUIRED', 'CREATED', 'SIGNATURE_REQUIRED', 'SUBMITTED', 'CONFIRMED', 'FAILED', 'REFUND_PENDING', 'REFUNDED')", name=op.f('ck_payment_records_payment_status')),
    sa.ForeignKeyConstraint(['blockchain_transaction_id'], ['blockchain_transactions.id'], name=op.f('fk_payment_records_blockchain_transaction_id_blockchain_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], name=op.f('fk_payment_records_bounty_id_bounties'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], name=op.f('fk_payment_records_contributor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['bounty_submissions.id'], name=op.f('fk_payment_records_submission_id_bounty_submissions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_records')),
    sa.UniqueConstraint('bounty_id', 'contributor_id', name='uq_payment_records_bounty_contributor'),
    sa.UniqueConstraint('submission_id', name='uq_payment_records_submission')
    )
    op.create_index(op.f('ix_payment_records_bounty_id'), 'payment_records', ['bounty_id'], unique=False)
    op.create_index(op.f('ix_payment_records_contributor_id'), 'payment_records', ['contributor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_records_contributor_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_bounty_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_submission_revisions_submission_id'), table_name='submission_revisions')
    op.drop_table('submission_revisions')
    op.drop_index('ix_blockchain_tx_status', table_name='blockchain_transactions')
    op.drop_index('ix_blockchain_tx_bounty_created', table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_user_id'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_submission_id'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_bounty_id'), table_name='blockchain_transactions')
    op.drop_index(op.f('ix_blockchain_transactions_assignment_id'), table_name='blockchain_transactions')
    op.drop_table('blockchain_transactions')
    op.drop_index(op.f('ix_bounty_submissions_contributor_id'), table_name='bounty_submissions')
    op.drop_index(op.f('ix_bounty_submissions_bounty_id'), table_name='bounty_submissions')
    op.drop_index(op.f('ix_bounty_submissions_assignment_id'), table_name='bounty_submissions')
    op.drop_table('bounty_submissions')
    op.drop_index(op.f('ix_dispute_evidence_dispute_id'), table_name='dispute_evidence')
    op.drop_table('dispute_evidence')
    op.drop_index('uq_assignments_one_live', table_name='bounty_assignments', postgresql_where=sa.text("status IN ('ACTIVE', 'COMPLETED')"))
    op.drop_index(op.f('ix_bounty_assignments_contributor_id'), table_name='bounty_assignments')
    op.drop_index(op.f('ix_bounty_assignments_bounty_id'), table_name='bounty_assignments')
    op.drop_table('bounty_assignments')
    op.drop_index('uq_disputes_one_open_per_bounty', table_name='disputes', postgresql_where=sa.text("status IN ('OPEN', 'UNDER_REVIEW')"))
    op.drop_index(op.f('ix_disputes_raised_by_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_bounty_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_table('bounty_view_daily')
    op.drop_index(op.f('ix_bounty_tags_tag'), table_name='bounty_tags')
    op.drop_index(op.f('ix_bounty_tags_bounty_id'), table_name='bounty_tags')
    op.drop_table('bounty_tags')
    op.drop_index(op.f('ix_bounty_skills_skill_name'), table_name='bounty_skills')
    op.drop_index(op.f('ix_bounty_skills_bounty_id'), table_name='bounty_skills')
    op.drop_table('bounty_skills')
    op.drop_table('bounty_escrows')
    op.drop_index(op.f('ix_bounty_bookmarks_user_id'), table_name='bounty_bookmarks')
    op.drop_index(op.f('ix_bounty_bookmarks_bounty_id'), table_name='bounty_bookmarks')
    op.drop_table('bounty_bookmarks')
    op.drop_index('uq_applications_one_active', table_name='bounty_applications', postgresql_where=sa.text("status IN ('PENDING', 'ACCEPTED')"))
    op.drop_index(op.f('ix_bounty_applications_contributor_id'), table_name='bounty_applications')
    op.drop_index(op.f('ix_bounty_applications_bounty_id'), table_name='bounty_applications')
    op.drop_index('ix_applications_bounty_status', table_name='bounty_applications')
    op.drop_table('bounty_applications')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_bounty_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_wallets_active_address_network', table_name='wallets', postgresql_where=sa.text("verification_status = 'VERIFIED'"))
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_public_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill_name'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_previous_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_reports_target', table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_status'), table_name='user_reports')
    op.drop_index(op.f('ix_user_reports_reporter_id'), table_name='user_reports')
    op.drop_table('user_reports')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_email_deliveries_user_id'), table_name='email_deliveries')
    op.drop_table('email_deliveries')
    op.drop_index('ix_bounties_status_published', table_name='bounties')
    op.drop_index(op.f('ix_bounties_status'), table_name='bounties')
    op.drop_index('ix_bounties_search_vector', table_name='bounties', postgresql_using='gin')
    op.drop_index('ix_bounties_requester_status', table_name='bounties')
    op.drop_index(op.f('ix_bounties_requester_id'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_difficulty'), table_name='bounties')
    op.drop_index(op.f('ix_bounties_category'), table_name='bounties')
    op.drop_table('bounties')
    op.drop_table('users')
    op.drop_table('simulated_ledger_entries')
    op.drop_table('processed_events')
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox_events')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
